fakeOnline:
  count: 7               # Базовый фейковый онлайн
  slots: 20              # Показываемые слоты (0 — не менять)
  min-fake: 3            # Минимальный фейк
  max-fake: 12           # Максимальный фейк
  update-interval: 5     # Интервал изменения (в секундах)